### ISSUE TITLE
Shared cache of preprocessed images

### ISSUE THREAD

**Issue by murraycutforth** [codercahol/chlamy-ImPi#5]
@codercahol I'm uploading a bunch of pre-segmented tif images to the google drive here: https://drive.google.com/drive/folders/1LB1znkc95zbgKAPVU2Rz4MMwbdcjtsBK?usp=drive_link 

Each file is a numpy array of shape (16, 24, NUM_TIMESTEPS, 20, 20), which you can load with `np.load(filename)`. The filename just corresponds to the name of each plate. Other than segmenting into individual wells and resampling to 20x20 resolution, nothing else has been done to the raw data.

Do you think this is a sensible shared cache to use as a starting point while we work out the next steps in the pipeline?

**Comment by codercahol** [comment]
Yeah, that sounds good to me.

Let's also add a cache of images that aren't pre-segmented that we can use to validate the segmentation pipeline. 

I also think it would be better if the default did not resample or resampled in a way that ~preserves the image dimensions. Because 20x20 roughly preserves the original image dimensions, I didn't mention it before when I first saw it, but I'd like it to be called out in some way so that it's more obvious that the resampling is happening.

**Comment by codercahol** [comment]
Low priority, but it might also be useful to have script that randomly grabs N photos and then tests the pipeline
